# Generated by Django 5.0 on 2024-02-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_botuser_email_botuser_name_botuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botname', models.CharField(max_length=500)),
                ('apitoken', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Groupinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('chat_id', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='BotUser',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
