# Generated by Django 5.0 on 2024-02-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_botinfo_groupinfo_delete_botuser_delete_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('group', models.ManyToManyField(to='main.groupinfo')),
            ],
        ),
    ]
