# Generated by Django 5.0 on 2024-02-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_botuser_video_delete_botinfo_remove_message_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=500)),
                ('trip_description', models.TextField()),
                ('trip_photo', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='BotUser',
        ),
    ]
