# Generated by Django 5.0 on 2024-04-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_question_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Course',
        ),
    ]
